### PR TITLE
Thread safety fix

### PR DESCRIPTION
**Pull request by juanjp600**
Some of my friends noticed that the game was considerably less stable when AEIOUCompany was installed. I've managed to collect a lot of logs that end when someone sends a message in text chat and the mod plays back the sound for it:

```
[Info   :AEIOUCompany] Queueing speak
[Info   :AEIOUCompany] Speak
[Info   :AEIOUCompany] Found player
[Info   :AEIOUCompany] Found AEIOUSpeakObject
[Info   :AEIOUCompany] Sending: msg=hot damn]
[Info   :AEIOUCompany] END
[Info   :AEIOUCompany] Setting up clip
[Info   :AEIOUCompany] Playing audio: AEIOUSpeakObject (UnityEngine.AudioSource)1
```

I took a look at the code and noticed that the Task that is spawned to communicate with SpeakServer also interacts with the engine's audio system, which I understand to not be thread-safe. I suspect the reason a Task is used is to make the game not freeze due to slow communication with SpeakServer.

This PR changes how this works to instead wait for the Task to end and then prepare and play back the sound on the main thread. This appears to have improved stability, friends have played an hour-long session without issue.

### CODE REVIEW

**Comment by Cart3r1234** [comment]
Glad someone was able to figure this out, my friends and I were experiencing the same issue but we couldn't figure out the actual cause, just that it was aeioucompany crashing.

**Comment by Cart3r1234** [comment]
Any word on this getting merged?  I've been using a build of the mod from this PR for a few weeks with friends, and it has completely fixed the crashes.  Having the fix in a published release would make using the mod in new packs/sharing modpacks with friends less tedious due to not having to manually replace aeioucompany with a fixed version.

**Comment by pestywanderer** [comment]
+1 to getting this merged, I've experienced this crash and also submitted logs to Bibendi. Would love to see this get fixed!

**Comment by ArbiterBibendi** [comment]
hot damn
Thanks for the PR!
Looks good, I'll get it built and uploaded and I'll ping you on discord once it's up.

**Pull request merged**
